- name: Fail when no Let's Encrypt mail has been configured
  ansible.builtin.fail:
    msg: 'variable "traefik_letsencrypt_mail" not set'
  when:
    - (traefik_letsencrypt_mail is not defined or traefik_letsencrypt_mail | trim == '')
    - traefik_tls == "acme"

- name: Prepare configuration directory
  ansible.builtin.file:
    path: "{{ traefik_dir }}"
    mode: "0755"
    state: directory

- name: Prepare directory for Let's Encrypt
  ansible.builtin.file:
    path: "{{ traefik_dir }}/acme"
    mode: "0755"
    state: directory

- name: Prepare directory for using own certs
  ansible.builtin.file:
    path: "{{ traefik_dir }}/certs"
    mode: "0755"
    state: directory

- name: Set ports configuration
  ansible.builtin.set_fact:
    ports_list:
      - "80:80"
      - "443:443"

- name: Add port 8443 when traefik_expose_flight is enabled
  ansible.builtin.set_fact:
    ports_list: "{{ ports_list + ['8443:8443'] }}"
  when: traefik_expose_flight == true

- name: Template configuration files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ traefik_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - "traefik.yml"
    - "traefik-timeseer.yml"
  register: traefik_config
  notify:
    - Signal Traefik Restart
    - Restart Traefik

- name: Run in a Docker container
  community.docker.docker_container:
    name: traefik
    image: "{{ traefik_image }}"
    pull: true
    state: started
    recreate: "{{ traefik_recreate_container }}"
    restart_policy: unless-stopped
    network_mode: "{{ traefik_network }}"
    ports: "{{ ports_list }}"
    volumes:
      - "{{ traefik_yml_path }}"
      - "{{ timeseer_yml_path }}"
      - "{{ acme_or_certs_path }}"
  vars:
    traefik_yml_path: "{{ traefik_dir }}/traefik.yml:/etc/traefik/traefik.yml"
    timeseer_yml_path: "{{ traefik_dir }}/traefik-timeseer.yml:/etc/traefik/traefik-timeseer.yml"
    acme_or_certs: "{{ 'acme' if traefik_tls == 'acme' else 'certs' }}"
    acme_or_certs_path: "{{ traefik_dir }}/{{ acme_or_certs }}:/etc/traefik/{{ acme_or_certs }}{{ ':z' if ansible_selinux.status == 'enabled' else '' }}"
    log_driver: journald
    log_options:
      tag: "{{ traefik_journal_tag }}"
    tty: true
