dependencies: []
galaxy_info:
  author: Diogo Lobo
  role_name: timeseer_reverse_proxy
  description: configure timeseer_reverse_proxy
  license: license (MIT)
  min_ansible_version: 2.5
  platforms:
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
    - name: Debian
      versions:
        - 11
