- name: Prepare a storage directory
  ansible.builtin.file:
    path: "{{ timeseer_dir }}/db"
    owner: 1001
    mode: "0755"
    state: directory
  when: timeseer_podman_volume | default('') | trim == ''

- name: Prepare a read-only data directory
  ansible.builtin.file:
    path: "{{ timeseer_dir }}/data"
    owner: 1001
    mode: "0755"
    state: directory

- name: Set storage path to podman volume
  ansible.builtin.set_fact:
    timeseer_storage_mount: "{{ timeseer_podman_volume }}"
  when: timeseer_podman_volume | default('') | trim != ''

- name: Set storage path to timeseer default storage_path
  ansible.builtin.set_fact:
    timeseer_storage_mount: "{{ timeseer_db_dir }}/db"
  when: timeseer_podman_volume | default('') | trim == ''

- name: Define timeseer volume list
  ansible.builtin.set_fact:
    timeseer_volume_list: "{{ timeseer_base_volumes + (timeseer_custom_toml_volume if timeseer_config_dir | default('') | trim != '' else []) }}"
  vars:
    timeseer_base_volumes:
      - "{{ timeseer_dir }}/data:/usr/src/app/data"
      - "{{ timeseer_storage_mount }}:/usr/src/app/db{{ ':z' if ansible_selinux['status'] == 'enabled' else '' }}"
    timeseer_custom_toml_volume:
      - "{{ timeseer_config_dir }}:/usr/src/app/config/:ro"

- name: Download demo data
  containers.podman.podman_container:
    name: timeseer-demo-data
    auto_remove: true
    detach: false
    image: "{{ timeseer_image }}"
    command: "python -m timeseer.cli demo-data"
    state: started
    volumes:
      - "{{ timeseer_dir }}/data:/usr/src/app/data"
    log_driver: journald
    log_options:
      tag: "{{ timeseer_journal_tag }}"
    tty: true
  when: timeseer_download_demo_data

- name: Template configuration for timeseer.network
  ansible.builtin.template:
    src: "timeseer.network"
    dest: "/etc/containers/systemd/timeseer.network"
    mode: "0644"

- name: Template configuration for timeseer-container.quadlet
  ansible.builtin.template:
    src: "timeseer-container.quadlet"
    dest: "/etc/containers/systemd/timeseer.container"
    mode: "0644"
  register: timeseer_container
  notify: Restart timeseer service

- name: Reload systemd daemon to ensure timeseer container is known
  ansible.builtin.systemd:
    daemon_reload: true
  when: timeseer_container.changed # noqa: no-handler

- name: Start and Enable Timeseer
  ansible.builtin.systemd:
    name: timeseer
    enabled: true
    state: started
  register: timeseer_service_status
