- name: Prepare a storage directory
  ansible.builtin.file:
    path: "{{ timeseer_dir }}/db"
    owner: 1001
    mode: "0755"
    state: directory
  when: timeseer_podman_volume | default('') | trim == ''

- name: Prepare a read-only data directory
  ansible.builtin.file:
    path: "{{ timeseer_dir }}/data"
    owner: 1001
    mode: "0755"
    state: directory

- name: Set storage path to podman volume
  ansible.builtin.set_fact:
    timeseer_storage_mount: "{{ timeseer_podman_volume }}"
  when: timeseer_podman_volume | default('') | trim != ''

- name: Set storage path to timeseer default storage_path
  ansible.builtin.set_fact:
    timeseer_storage_mount: "{{ timeseer_db_dir }}/db"
  when: timeseer_podman_volume | default('') | trim == ''

- name: Define timeseer volume list
  ansible.builtin.set_fact:
    timeseer_volume_list: "{{ timeseer_base_volumes + (timeseer_custom_toml_volume if timeseer_config_dir | default('') | trim != '' else []) }}"
  vars:
    timeseer_base_volumes:
      - "{{ timeseer_dir }}/data:/usr/src/app/data"
      - "{{ timeseer_storage_mount }}:/usr/src/app/db{{ ':z' if ansible_selinux['status'] == 'enabled' else '' }}"
    timeseer_custom_toml_volume:
      - "{{ timeseer_config_dir }}:/usr/src/app/config/:ro"

- name: Create a podman network
  containers.podman.podman_network:
    name: "{{ timeseer_network }}"

- name: Download demo data
  containers.podman.podman_container:
    name: timeseer-demo-data
    auto_remove: true
    detach: false
    image: "{{ timeseer_image }}"
    command: "python -m timeseer.cli demo-data"
    state: started
    volumes:
      - "{{ timeseer_dir }}/data:/usr/src/app/data"
    log_driver: journald
    log_options:
      tag: "{{ timeseer_journal_tag }}"
    tty: true
  when: timeseer_download_demo_data

- name: Create timeseer quadlet container
  containers.podman.podman_container:
    name: timeseer
    image: "{{ timeseer_image }}"
    user: "1001"
    network: "{{ timeseer_network }}"
    volumes: "{{ timeseer_volume_list }}"
    state: quadlet
    ports: "{{ timeseer_ports if timeseer_ports and timeseer_ports != '' else omit }}"
    log_options:
      tag: "{{ timeseer_journal_tag }}"
    tty: true

- name: Template configuration files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/containers/systemd/ts-container.container"
    mode: "0644"
  loop:
    - "timeseer-container.quadlet.j2"
  register: timeseer_j2
  notify:
    - Signal daemon Restart
    - Reload systemd daemon
    - Restart timeseer service

- name: Flush Handlers to apply changes immediately
  ansible.builtin.meta: flush_handlers

- name: Enable timeseer-container service
  ansible.builtin.systemd:
    name: ts-container
    enabled: true

- name: Start timeseer-container service
  ansible.builtin.systemd:
    name: ts-container
    state: started
