- name: Prepare configuration directory
  ansible.builtin.file:
    path: "{{ timeseer_reverse_proxy_dir }}"
    state: directory
    mode: "0755"

- name: Create a file for environment variables
  ansible.builtin.file:
    path: "{{ timeseer_reverse_proxy_dir }}/env"
    state: touch
    mode: "0644"

- name: Set config_dir for Timeseer Reverse Proxy
  ansible.builtin.set_fact:
    config_dir: "{{ timeseer_reverse_proxy_config_dir | default(timeseer_reverse_proxy_dir) }}"

- name: Define timeseer-reverse-proxy volume list
  ansible.builtin.set_fact:
    reverse_proxy_volume_list: "{{ custom_toml_volume if timeseer_reverse_proxy_config_dir | default('') | trim != '' else [] }}"
  vars:
    config_dir: "{{ timeseer_reverse_proxy_config_dir | default(timeseer_reverse_proxy_dir) }}"
    selinux_suffix: "{{ ':z' if ansible_selinux['status'] == 'enabled' else '' }}"
    custom_toml_volume:
      - "{{ config_dir }}:/usr/src/app/proxy-config{{ selinux_suffix }}"

- name: Create a Timeseer Reverse Proxy quadlet file
  containers.podman.podman_container:
    name: timeseer-reverse-proxy
    image: "{{ timeseer_reverse_proxy_image }}"
    command: "/usr/bin/timeseer-reverse-proxy --config-file /usr/src/app/Timeseer-reverse-proxy.toml"
    state: quadlet
    pull: "{{ timeseer_reverse_proxy_image_pull }}"
    network: "{{ timeseer_reverse_proxy_network }}"
    volumes: "{{ reverse_proxy_volume_list }}"
    log_driver: journald
    log_options:
      tag: "{{ timeseer_reverse_proxy_journal_tag }}"
    env_file: "{{ timeseer_reverse_proxy_dir }}/env"
    tty: true
    ports: "{{ timeseer_reverse_proxy_ports if timeseer_reverse_proxy_ports and timeseer_reverse_proxy_ports != '' else omit }}"

- name: Template configuration files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/containers/systemd/ts-reverse-proxy-container.container"
    mode: "0644"
  loop:
    - "timeseer-reverse-proxy-container.quadlet.j2"
  register: timeseer_proxy_j2
  notify:
    - Signal daemon Restart for timeseer-reverse-proxy
    - Reload systemd daemon for timeseer-reverse-proxy
    - Restart timeseer-reverse-proxy

- name: Flush  timeseer-reverse-proxy Handlers to apply changes immediately
  ansible.builtin.meta: flush_handlers

- name: Enable timeseer-reverse-proxy-container service
  ansible.builtin.systemd:
    name: ts-reverse-proxy-container
    enabled: true

- name: Start timeseer-reverse-proxy-container service
  ansible.builtin.systemd:
    name: ts-reverse-proxy-container
    state: started
