- name: Prepare configuration directory
  ansible.builtin.file:
    path: "{{ timeseer_reverse_proxy_dir }}"
    state: directory
    mode: "0755"

- name: Create a file for environment variables
  ansible.builtin.file:
    path: "{{ timeseer_reverse_proxy_dir }}/env"
    state: touch
    mode: "0644"

- name: Template quadlet
  ansible.builtin.template:
    src: "timeseer-reverse-proxy-container.quadlet"
    dest: "/etc/containers/systemd/timeseer-reverse-proxy.container"
    mode: "0644"
  register: timeseer_reverse_proxy_container
  notify:
    - Restart timeseer-reverse-proxy service

- name: Reload systemd daemon to ensure timeseer-reverse-proxy container is known
  ansible.builtin.systemd:
    daemon_reload: true
  when: timeseer_reverse_proxy_container.changed # noqa: no-handler

- name: Start and Enable Timeseer-reverse-proxy
  ansible.builtin.systemd:
    name: timeseer-reverse-proxy
    enabled: true
    state: started
  register: timeseer_reverse_proxy_status
