argument_specs:
  timeseer_setup:
    short_description: Configure and prepare timeseer environment
    description:
      - Prepares directories and sets up podman-related configurations for timeseer.
      - Ensures necessary directories are in place and configures storage paths based on given conditions.

    options:
      timeseer_dir:
        description:
          - The base directory for timeseer configurations and data.
        type: str
        default: "/opt/timeseer"

      timeseer_db_dir:
        description:
          - Directory for timeseer database storage.
          - Used when podman volume is not specified.
        type: str
        default: "/opt/timeseer"

      timeseer_podman_volume:
        description:
          - Optional podman volume for timeseer data storage.
          - If defined, it is used as the primary storage path.
        type: str
        default: ""

      timeseer_image:
        description:
          - The podman image to use for timeseer.
        type: str
        default: "container.timeseer.ai/timeseer"

      timeseer_config_dir:
        description:
          - Directory for custom timeseer configuration files.
        type: str
        default: ""

      timeseer_network:
        description:
          - Name of the podman network to be used by timeseer.
        type: str
        default: "timeseer"

      timeseer_journal_tag:
        description:
          - Tag to use for logging purposes in the timeseer container.
        type: str
        default: "TIMESEER"

      timeseer_download_demo_data:
        description:
          - Whether to download demo data for timeseer.
        type: bool
        default: false

      timeseer_ports:
        description:
          - "Custom port mapping for the timeseer container. Format should match podman's port mapping format, e.g., '8080:8080'."
        type: str
        default: ""

      timeseer_image_pull:
        description: Specifies when to pull the container image for the Timeseer data service, allowing control over the image version used.
        type: str
        default: "missing"
      options:
        - option:
            name: "missing"
            description: "Pulls the image if not present locally. This is the default setting."
        - option:
            name: "always"
            description: "Always pulls the image to ensure the latest version."
        - option:
            name: "never"
            description: "Does not pull the image, using the local version if available."
        - option:
            name: "newer"
            description: "Pulls the image only if the registry version is newer than the local one."
