- name: Signal daemon Restart for traefik
  ansible.builtin.set_fact:
    daemon_reload: true
  when: item.changed
  loop: "{{ traefik_config.results }}"
  loop_control:
    label: "{{ item.dest }}"

- name: Reload systemd daemon for traefik
  ansible.builtin.systemd:
    daemon_reload: "{{ daemon_reload }}"
  when: daemon_reload | default(false) | bool

- name: Restart traefik service
  ansible.builtin.systemd:
    name: ts-traefik-proxy-container
    state: restarted
