- name: Signal Traefik Restart
  ansible.builtin.set_fact:
    traefik_recreate_container: true
  with_items: "{{ traefik_config.results }}"
  when: item is changed
  loop_control:
    label: "{{ item.dest }}"

- name: Restart Traefik
  containers.podman.podman_container:
    name: traefik
    image: "{{ traefik_image }}"
    state: started
    recreate: "{{ traefik_recreate_container }}"
    restart_policy: unless-stopped
    network_mode: "{{ traefik_network }}"
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - "{{ traefik_dir }}/traefik.yml:/etc/traefik/traefik.yml"
      - "{{ traefik_dir }}/traefik-timeseer.yml:/etc/traefik/traefik-timeseer.yml"
      - "{{ traefik_dir }}/{{ 'acme' if traefik_tls == 'acme' else 'certs' }}:/etc/traefik/{{ 'acme' if traefik_tls == 'acme' else 'certs' }}{{ ':z' if ansible_selinux.status == 'enabled' else '' }}"
    log_driver: journald
    log_options:
      tag: "{{ traefik_journal_tag }}"
    tty: true
