- name: Restart traefik service
  ansible.builtin.systemd:
    name: traefik
    state: restarted
  when: traefik_container_config is not changed

- name: Restart traefik
  ansible.builtin.systemd:
    name: traefik
    state: restarted
