---
timeseer_data_service_dir: "/opt/timeseer/data-service"
timeseer_data_service_docker_volume: ""
timeseer_data_service_toml_dir: ""
timeseer_data_service_enable: false
timeseer_data_service_image: "container.timeseer.ai/timeseer"
timeseer_data_service_ports: []
timeseer_data_service_network: "timeseer"
timeseer_data_service_journal_tag: "TIMESEER-DS"
timeseer_data_service_image_pull: true
