---

log:
  level: INFO

accessLog:
  bufferingSize: 100

providers:
  file:
     filename: "/etc/traefik/traefik-timeseer.yml"

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
{% if traefik_expose_flight %}
  flight:
    address: ":8443"
{% endif %}


certificatesResolvers:
  timeseer-le:
    acme:
      email: "{{ traefik_letsencrypt_mail }}"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: http