- name: Fail when no Let's Encrypt mail has been configured
  ansible.builtin.fail:
    msg: 'variable "traefik_letsencrypt_mail" not set'
  when:
    - (traefik_letsencrypt_mail is not defined or traefik_letsencrypt_mail | trim == '')
    - traefik_tls == "acme"

- name: Prepare configuration directory
  ansible.builtin.file:
    path: "{{ traefik_dir }}"
    mode: "0755"
    state: directory

- name: Prepare directory for Let's Encrypt
  ansible.builtin.file:
    path: "{{ traefik_dir }}/acme"
    mode: "0755"
    state: directory

- name: Prepare directory for using own certs
  ansible.builtin.file:
    path: "{{ traefik_dir }}/certs"
    mode: "0755"
    state: directory

- name: Set ports configuration
  ansible.builtin.set_fact:
    ports_list:
      - "80:80"
      - "443:443"

- name: Add port 8443 when traefik_expose_flight is enabled
  ansible.builtin.set_fact:
    ports_list: "{{ ports_list + ['8443:8443'] }}"
  when: traefik_expose_flight

- name: Define traefik_tls
  ansible.builtin.set_fact:
    acme_or_certs: "{{ 'acme' if traefik_tls == 'acme' else 'certs' }}"

- name: Define traefik volume list
  ansible.builtin.set_fact:
    traefik_volume_list:
      - "{{ traefik_dir }}/traefik.yml:/etc/traefik/traefik.yml"
      - "{{ traefik_dir }}/traefik-timeseer.yml:/etc/traefik/traefik-timeseer.yml"
      - "{{ traefik_dir }}/{{ acme_or_certs }}:/etc/traefik/{{ acme_or_certs }}{{ ':z' if ansible_selinux.status == 'enabled' else '' }}"

- name: Template Traefik configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - src: "traefik.yml"
      dest: "{{ traefik_dir }}/traefik.yml"
    - src: "traefik-timeseer.yml"
      dest: "{{ traefik_dir }}/traefik-timeseer.yml"
  notify:
    - Restart traefik

- name: Template Traefik container file
  ansible.builtin.template:
    src: "traefik-container.quadlet"
    dest: "/etc/containers/systemd/traefik.container"
    mode: "0644"
  register: traefik_container_config

- name: Reload systemd daemon to ensure traefik container is known
  ansible.builtin.systemd:
    daemon_reload: true
  when: traefik_container_config.changed # noqa: no-handler

- name: Start and Enable traefik
  ansible.builtin.systemd:
    name: traefik
    enabled: true
    state: started
  register: traefik_status
