- name: Fail when no Let's Encrypt mail has been configured
  ansible.builtin.fail:
    msg: 'variable "traefik_letsencrypt_mail" not set'
  when:
    - (traefik_letsencrypt_mail is not defined or traefik_letsencrypt_mail | trim == '')
    - traefik_tls_enable
    - traefik_tls == "acme"

- name: Prepare configuration directory
  ansible.builtin.file:
    path: "{{ traefik_dir }}"
    mode: "0755"
    state: directory

- name: Define TLS directory
  ansible.builtin.set_fact:
    tls_config_dir: "{{ 'acme' if traefik_tls == 'acme' else 'certs' }}"
  when: traefik_tls_enable

- name: Prepare directory for TLS
  ansible.builtin.file:
    path: "{{ traefik_dir }}/{{ tls_config_dir }}"
    mode: "0755"
    state: directory
  when: traefik_tls_enable

- name: Set default ports configuration
  ansible.builtin.set_fact:
    ports_list: >
      {{
        [
          "80:80",
          "443:443"
        ]
        + (["8443:8443"] if traefik_expose_flight else [])
      }}

- name: Define traefik volume list
  ansible.builtin.set_fact:
    traefik_volume_list:
      - "{{ traefik_dir }}/traefik.yml:/etc/traefik/traefik.yml"
      - "{{ traefik_dir }}/traefik-timeseer.yml:/etc/traefik/traefik-timeseer.yml"

- name: Define TLS volume
  ansible.builtin.set_fact:
    traefik_tls_volume: "{{ traefik_dir }}/{{ tls_config_dir }}:/etc/traefik/{{ tls_config_dir }}{{ ':z' if ansible_selinux.status == 'enabled' else '' }}"
  when: traefik_tls_enable

- name: Template Traefik configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - src: "traefik.yml"
      dest: "{{ traefik_dir }}/traefik.yml"
    - src: "traefik-timeseer.yml"
      dest: "{{ traefik_dir }}/traefik-timeseer.yml"
  notify:
    - Restart traefik

- name: Template Traefik container file
  ansible.builtin.template:
    src: "traefik-container.quadlet"
    dest: "/etc/containers/systemd/traefik.container"
    mode: "0644"
  register: traefik_container_config

- name: Reload systemd daemon to ensure traefik container is known
  ansible.builtin.systemd:
    daemon_reload: true
  when: traefik_container_config.changed # noqa: no-handler

- name: Start and Enable traefik
  ansible.builtin.systemd:
    name: traefik
    enabled: true
    state: started
  register: traefik_status
