- name: Fail when no Let's Encrypt mail has been configured
  ansible.builtin.fail:
    msg: 'variable "traefik_letsencrypt_mail" not set'
  when: traefik_letsencrypt_mail is not defined or traefik_letsencrypt_mail | trim == ''

- name: Prepare configuration directory
  ansible.builtin.file:
    path: "{{ traefik_dir }}"
    mode: "0755"
    state: directory

- name: Prepare directory for Let's Encrypt
  ansible.builtin.file:
    path: "{{ traefik_dir }}/acme"
    mode: "0755"
    state: directory

- name: Prepare directory for using own certs
  ansible.builtin.file:
    path: "{{ traefik_dir }}/certs"
    mode: "0755"
    state: directory

- name: Template configuration files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ traefik_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - "traefik.yml"
    - "traefik-timeseer.yml"
  register: traefik_config
  notify:
    - Signal Traefik Restart
    - Restart Traefik

- name: Run traefik in a Podman container
  containers.podman.podman_container:
    name: traefik
    image: "{{ traefik_image }}"
    state: started
    recreate: "{{ traefik_recreate_container }}"
    restart_policy: unless-stopped
    network_mode: "{{ traefik_network }}"
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - "{{ traefik_dir }}/traefik.yml:/etc/traefik/traefik.yml"
      - "{{ traefik_dir }}/traefik-timeseer.yml:/etc/traefik/traefik-timeseer.yml"
      - "{{ traefik_dir }}/{{ 'acme' if traefik_tls == 'acme' else 'certs' }}:/etc/traefik/{{ 'acme' if traefik_tls == 'acme' else 'certs' }}{{ ':z' if ansible_selinux.status == 'enabled' else '' }}"
    log_driver: journald
    log_options:
      tag: "{{ traefik_journal_tag }}"
    tty: true
