dependencies: []
galaxy_info:
  author: Jeroen Hoekx, Diogo Lobo
  role_name: timeseer_reverse_proxy
  description: configure timeseer_reverse_proxy
  license: license (MIT)
  min_ansible_version: "2.5"
