- name: Signal Traefik Restart
  ansible.builtin.set_fact:
    traefik_recreate_container: true
  with_items: "{{ traefik_config.results }}"
  when: item is changed
  loop_control:
    label: "{{ item.dest }}"

- name: Restart Traefik
  community.docker.docker_container:
    name: traefik
    image: "{{ traefik_image }}"
    pull: true
    state: started
    recreate: "{{ traefik_recreate_container }}"
    restart_policy: unless-stopped
    network_mode: "{{ traefik_network }}"
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - "{{ traefik_yml_path }}"
      - "{{ timeseer_yml_path }}"
      - "{{ acme_or_certs_path }}"
  vars:
    traefik_yml_path: "{{ traefik_dir }}/traefik.yml:/etc/traefik/traefik.yml"
    timeseer_yml_path: "{{ traefik_dir }}/traefik-timeseer.yml:/etc/traefik/traefik-timeseer.yml"
    acme_or_certs: "{{ 'acme' if traefik_tls == 'acme' else 'certs' }}"
    acme_or_certs_path: "{{ traefik_dir }}/{{ acme_or_certs }}:/etc/traefik/{{ acme_or_certs }}{{ ':z' if ansible_selinux.status == 'enabled' else '' }}"
    log_driver: journald
    log_options:
      tag: "{{ traefik_journal_tag }}"
    tty: true
