http:
  services:
    timeseer:
      loadBalancer:
        servers:
        - url: "http://timeseer:8080"
{% if traefik_timeseer_reverse_proxy_enable %}
    reverseProxy:
      loadBalancer:
        servers:
        - url: "http://timeseer-reverse-proxy:8000"
{% endif %}
{% if traefik_expose_flight %}
    flight:
      loadBalancer:
        servers:
        - url: "h2c://timeseer:8081"
{% endif %}

{% if traefik_basic_auth_enable %}
  middlewares:
    auth:
      basicAuth:
        users:
{% for user in traefik_basic_auth_users %}
          - "{{ user }}"
{% endfor %}
        headerField: "X-Forwarded-User"
{% endif %}

  routers:
    timeseer:
      entryPoints:
{% if traefik_tls_enable %}
      - "https"
{% else %}
      - "http"
{% endif %}
      rule: "Host(`{{ traefik_host }}`)"
{% if traefik_basic_auth_enable %}
      middlewares:
      - "auth@file"
{% endif %}
{% if traefik_timeseer_reverse_proxy_enable %}
      service: reverseProxy
{% else %}
      service: timeseer
{% endif %}
{% if traefik_tls_enable %}
{% if traefik_tls == "acme" %}
      tls:
        certResolver: timeseer-le
{% elif traefik_tls == "certs" %}
      tls: {}
{% endif %}
{% endif %}

{% if traefik_expose_flight %}
    flight:
      entryPoints:
      - "flight"
      rule: "Host(`{{ traefik_host }}`)"
      service: flight
{% if traefik_tls_enable %}
{% if traefik_tls == "acme" %}
      tls:
        certResolver: timeseer-le
{% elif traefik_tls == "certs" %}
      tls: {}
{% endif %}
{% endif %}
{% endif %}

    timeseer-public-api:
      entryPoints:
{% if traefik_tls_enable %}
      - "https"
{% else %}
      - "http"
{% endif %}
      rule: "Host(`{{ traefik_host }}`) && PathPrefix(`/public/api`)"
{% if traefik_timeseer_reverse_proxy_enable %}
      service: reverseProxy
{% else %}
      service: timeseer
{% endif %}
{% if traefik_tls_enable %}
{% if traefik_tls == "acme" %}
      tls:
        certResolver: timeseer-le
{% elif traefik_tls == "certs" %}
      tls: {}
{% endif %}
{% endif %}

{% if traefik_tls_enable and traefik_tls == "certs" %}
tls:
  certificates:
    - certFile: "/etc/traefik/certs/{{ traefik_cert_file_name }}"
      keyFile: "/etc/traefik/certs/{{ traefik_key_file_name }}"
{% endif %}
