---

log:
  level: INFO

accessLog:
  bufferingSize: 100

providers:
  file:
    filename: "/etc/traefik/traefik-timeseer.yml"

entryPoints:
{% if traefik_tls_enable %}
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
{% else %}
  http:
    address: ":80"
{% endif %}
{% if traefik_expose_flight %}
  flight:
    address: ":8443"
{% endif %}

{% if traefik_tls_enable and traefik_tls == "acme" %}
certificatesResolvers:
  timeseer-le:
    acme:
      email: "{{ traefik_letsencrypt_mail }}"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: http
{% endif %}
