http:
  services:
    timeseer:
      loadBalancer:
        servers:
          - url: "http://timeseer:8080"
    {% if traefik_timeseer_reverse_proxy_enable %}
    reverseProxy:
      loadBalancer:
        servers:
          - url: "http://timeseer-reverse-proxy:8000"
    {% endif %}
    {% if traefik_expose_flight %}
    flight:
      loadBalancer:
        servers:
          - url: "h2c://timeseer:8081"
    {% endif %}

  {% if traefik_basic_auth_enable %}
  middlewares:
    auth:
      basicAuth:
        users:
          {% for user in traefik_basic_auth_users %}
          - "{{ user }}"
          {% endfor %}
        headerField: "X-Forwarded-User"
  {% endif %}

  routers:
    timeseer:
      entryPoints:
        - "https"
      {% if traefik_basic_auth_enable %}
      middlewares:
        - "auth@file"
      {% endif %}
      {% if not traefik_timeseer_reverse_proxy_enable %}
      service: timeseer
      {% else %}
      service: reverseProxy
      {% endif %}
      {% if traefik_tls == "acme" %}
      rule: "Host(`{{ traefik_host }}`)"
      tls:
        certResolver: timeseer-le
      {% elif traefik_tls == "certs" %}
      rule: "Host(`{{ traefik_host }}`)"
      tls: {}
      {% endif %}
    {% if traefik_expose_flight and traefik_tls == "acme" %}
    flight:
      entryPoints:
        - "flight"
      service: flight
      rule: "Host(`{{ traefik_host }}`)"
      tls:
        certResolver: timeseer-le
    {% elif traefik_expose_flight and traefik_tls == "certs" %}
    flight:
      entryPoints:
        - "flight"
      service: flight
      rule: "Host(`{{ traefik_host }}`)"
      tls: {}
    {% endif %}
    timeseer-public-api:
      entryPoints:
        - {% if traefik_tls == "acme" or traefik_tls == "certs" %}"https"{% else %}"web"{% endif %}
      service: {% if not traefik_timeseer_reverse_proxy_enable %}timeseer{% else %}reverseProxy{% endif %}
      rule: "Host(`{{ traefik_host }}`) && PathPrefix(`/public/api`)"
      {% if traefik_tls == "acme" %}
      tls:
        certResolver: timeseer-le
      {% elif traefik_tls == "certs" %}
      tls: {}
      {% endif %}

  {% if traefik_tls == "certs" %}
  tls:
    certificates:
      - certFile: "/etc/traefik/certs/{{ traefik_cert_file_name }}"
        keyFile: "/etc/traefik/certs/{{ traefik_key_file_name }}"
  {% endif %}
