name: Collection build and tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ansible-version:
          - "2.18.0"
        runner-python-version:
          - 3.12
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.runner-python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.runner-python-version }}

      - name: Install specific Ansible version ${{ matrix.ansible-version }}
        run: |
          pip install ansible-core==${{ matrix.ansible-version }}

      - name: Install dependencies
        run: ansible-galaxy collection install community.docker containers.podman

      - name: Install Ansible lint
        run: >-
          pip install ansible-lint

      - name: Run ansible-lint
        run: >-
          ansible-lint

  build:
    name: Build timeseer collection
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ansible-version:
          - "2.18.0"
        runner-python-version:
          - 3.12
    needs: lint
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install specific Ansible version ${{ matrix.ansible-version }}
        run: |
          pip install ansible-core==${{ matrix.ansible-version }}

      - name: Build Docker collection
        run: ansible-galaxy collection build ./timeseer/docker/ -v --output-path ./artifacts

      - name: Build podman collection
        run: ansible-galaxy collection build ./timeseer/podman/ -v  --output-path ./artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: collections
          path: artifacts/*.tar.gz
          retention-days: 7
