name: Collection release and publish
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  build:
    name: Build timeseer collection
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        runner-os:
          - ubuntu-22.04
        ansible-version:
          - "2.17.1"
        runner-python-version:
          - 3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.runner-python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.runner-python-version }}

      - name: Install specific Ansible version ${{ matrix.ansible-version }}
        run: |
          pip install ansible-core==${{ matrix.ansible-version }}

      - name: Build Docker collection
        run: ansible-galaxy collection build ./timeseer/docker/ -v --output-path ./artifacts

      - name: Build podman collection
        run: ansible-galaxy collection build ./timeseer/podman/ -v  --output-path ./artifacts

      - name: Publish Docker Collection to Ansible Galaxy
        run: ansible-galaxy collection publish ./artifacts/timeseer-docker-*.tar.gz --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }}

      - name: Publish Podman Collection to Ansible Galaxy
        run: ansible-galaxy collection publish ./artifacts/timeseer-podman-*.tar.gz --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
