- name: Reload systemd daemon for timeseer-data-service-container service
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart timeseer-data-service-container
  ansible.builtin.systemd:
    name: timeseer-data-service-container
    state: restarted
